# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            sudo su -c 'echo "deb http://http.debian.net/debian jessie-backports main" >> /etc/apt/sources.list'
            sudo apt-get update
            sudo apt-get install -t jessie-backports openjdk-8-jdk
      - restore_cache:
          keys:
          - v7-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v7-dependencies-
      - run:
          name: Local npm install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v6-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run e2e tests against server set in API_BASE_URL env var.
          command: API_BASE_URL=https://tpp-reference-server.herokuapp.com/open-banking/v1.1 REDIRECT_DELAY_SECONDS=1 npm run e2e
      - run:
          name: Run unit tests
          command: npm run unit
      - run:
          name: Run eslint checks
          command: npm run eslint
